"use client";
import { FormEvent, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import Link from "next/link";
import { createClient } from "@/lib/supabase/client";
export default function SignInPage(){
 const router=useRouter(); const params=useSearchParams(); const next=params.get("next")||"/account";
 const [mode,setMode]=useState<"signin"|"signup">("signin"); const [name,setName]=useState(""); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [confirm,setConfirm]=useState(""); const [busy,setBusy]=useState(false); const [message,setMessage]=useState(""); const [resend,setResend]=useState(false);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMessage("");setResend(false);try{const supabase=createClient();if(mode==="signup"){if(!name.trim())throw new Error("Enter your full name.");if(password!==confirm)throw new Error("Passwords do not match.");const {data,error}=await supabase.auth.signUp({email,password,options:{data:{full_name:name.trim()},emailRedirectTo:window.location.origin+next}});if(error)throw error;if(!data.session){setMessage("Your account was created. Please open the confirmation email we sent, confirm your address, then sign in.");setMode("signin");}else{router.replace(next);router.refresh();}}else{const {error}=await supabase.auth.signInWithPassword({email,password});if(error){const code=(error as {code?:string}).code;if(code==="email_not_confirmed"||error.message.toLowerCase().includes("email not confirmed")){setResend(true);setMessage("Your account exists, but its email address is not confirmed. Confirm the email first, or resend the confirmation link below.");}else if(code==="invalid_credentials"){setMessage("Email or password is incorrect. Check both fields, or use Forgot password.");}else throw error;}else{router.replace(next);router.refresh();}}}catch(err){setMessage(err instanceof Error?err.message:"Authentication failed. Please try again.");}finally{setBusy(false);}}
 async function resendConfirmation(){if(!email.trim()){setMessage("Enter the email address you used to create your account.");return;}setBusy(true);try{const {error}=await createClient().auth.resend({type:"signup",email,options:{emailRedirectTo:window.location.origin+next}});if(error)throw error;setMessage("Confirmation email requested. Check your inbox and spam folder, open the link, then return here to sign in.");setResend(false);}catch(err){setMessage(err instanceof Error?err.message:"Unable to resend confirmation. Try again later.");}finally{setBusy(false);}}
 async function reset(){if(!email.trim()){setMessage("Enter your email first.");return;}try{const {error}=await createClient().auth.resetPasswordForEmail(email,{redirectTo:window.location.origin+"/reset-password"});if(error)throw error;setMessage("If this email is registered, password reset instructions have been sent.");}catch(err){setMessage(err instanceof Error?err.message:"Unable to send reset email.");}}
 return <main className="shell"><section className="panel"><Link href="/index.html" className="auth-brand"><img src="/oranos-crest.png" alt="ORANOS crest"/><span>ORANOS <small>COMMUNITY</small></span></Link><div className="gold">ORANOS COMMUNITY</div><h1>MEMBER ACCESS</h1><p className="muted">Fitness. Mindset. Lifestyle. Discipline.</p><div className="actions"><button className="action" type="button" onClick={()=>{setMode("signin");setMessage("");setResend(false);}}>Sign in</button><button className="action" type="button" onClick={()=>{setMode("signup");setMessage("");setResend(false);}}>Create account</button></div><form onSubmit={submit} style={{display:"grid",gap:14,marginTop:20}}>{mode==="signup"&&<label>Full name<input required value={name} onChange={e=>setName(e.target.value)} autoComplete="name" style={field}/></label>}<label>Email<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email" style={field}/></label><label>Password<input required type="password" minLength={8} value={password} onChange={e=>setPassword(e.target.value)} autoComplete={mode==="signup"?"new-password":"current-password"} style={field}/></label>{mode==="signup"&&<label>Confirm password<input required type="password" minLength={8} value={confirm} onChange={e=>setConfirm(e.target.value)} autoComplete="new-password" style={field}/></label>}<button className="action primary" disabled={busy} type="submit">{busy?"Please wait…":mode==="signup"?"Create account":"Sign in"}</button></form>{resend&&<button type="button" onClick={resendConfirmation} disabled={busy} className="resend-button">{busy?"Sending…":"Resend confirmation email"}</button>}{mode==="signin"&&<button type="button" onClick={reset} className="reset-button">Forgot password?</button>}<p aria-live="polite" className="muted">{message}</p><Link href="/community.html">← Existing community page</Link></section></main>}
const field={display:"block",width:"100%",padding:12,marginTop:7,borderRadius:8,border:"1px solid #555",background:"#101217",color:"#fff"} as const;
