import { redirect } from "next/navigation";
import { createServerClient } from "@supabase/ssr";
import { cookies } from "next/headers";
import { getSupabaseConfig } from "@/lib/supabase/config";
const pillars = [{ name: "FITNESS", detail: "Train strength, endurance, mobility, and recovery.", mark: "01" }, { name: "MINDSET", detail: "Build focus, resilience, and intentional thinking.", mark: "02" }, { name: "LIFESTYLE", detail: "Shape daily habits that support the life you want.", mark: "03" }, { name: "DISCIPLINE", detail: "Keep promises to yourself through consistent action.", mark: "04" }];
export default async function AccountPage() {
  const jar = await cookies(); const { url, key } = getSupabaseConfig();
  const supabase = createServerClient(url, key, { cookies: { getAll() { return jar.getAll(); }, setAll(values) { try { values.forEach(({ name, value, options }) => jar.set(name, value, options)); } catch {} } } });
  const { data: { user } } = await supabase.auth.getUser(); if (!user) redirect("/sign-in");
  const name = String(user.user_metadata?.full_name || "Member").trim();
  return <main className="dashboard"><header className="dash-header"><a className="brand" href="/community.html"><img src="/oranos-crest.png" alt="ORANOS crest" className="account-logo"/><span>ORANOS <small>COMMUNITY</small></span></a><div className="header-user"><span>{name}</span><form action="/auth/signout" method="post"><button className="quiet-button" type="submit">Sign out ↗</button></form></div></header><section className="welcome"><div className="eyebrow">MEMBER SPACE / 01</div><h1>Welcome back, <em>{name}.</em></h1><p>Your standard is built in the choices you repeat. Choose a pillar and take your next step.</p><div className="welcome-actions"><a className="gold-button" href="/titan-challenge">Explore Titan Challenge <span>↗</span></a><a className="text-link" href="/community.html">Explore community →</a></div></section><section className="section-head"><div><div className="eyebrow">THE ORANOS STANDARD</div><h2>Four pillars. One direction.</h2></div><span className="section-index">01 — 04</span></section><section className="pillar-grid">{pillars.map(p => <article className="pillar-card" key={p.name}><div className="pillar-top"><span>{p.mark}</span><span className="pillar-symbol">↗</span></div><h3>{p.name}</h3><p>{p.detail}</p></article>)}</section><section className="member-panel"><div><div className="eyebrow">YOUR MEMBERSHIP</div><h2>Make consistency visible.</h2><p>Challenge submissions and membership status will appear here when those features are connected. No progress is fabricated or assumed.</p></div><div className="member-status"><span className="status-dot" /> ACCOUNT ACTIVE</div></section><footer className="dash-footer"><span>ORANOS — FORGE YOUR STANDARD.</span><a href="/community.html">Community home ↗</a></footer></main>;
}